#  Main header!
#  Line 2

[songs]
	[songs.Ancestry_Lena_Raine]
		triggers = [ "Dimension-nether" ]
	[songs.C418_Ballad_of_the_Cats_Minecraft_Volume_Beta_NycrypticProject]
		triggers = [ "Dimension-nether" ]
	[songs.C418_Blocks_Minecraft_Volume_Beta_NycrypticProject]
		triggers = [ "Dimension-overworld" ]
	[songs.C418_Cat_Minecraft_Volume_Alpha_SMORT]
		triggers = [ "Dimension-overworld" ]
	[songs.C418_Concrete_Halls_Minecraft_Volume_Beta_NycrypticProject]
		triggers = [ "Dimension-nether" ]
	[songs.C418_Dead_Voxel_Minecraft_Volume_Beta_NycrypticProject]
		triggers = [ "Dimension-nether" ]
	[songs.C418_Equinoxe_Minecraft_Volume_Alpha_SMORT]
		triggers = [ "Time-night" ]
	[songs.C418_Stal_Minecraft_Volume_Beta_NycrypticProject]
		triggers = [ "Dimension-overworld" ]
	[songs.C418-Aria-Math-_Minecraft-Volume-Beta_-NycrypticProject]
		triggers = [ "Raining" ]
	[songs.C418_Strad_Minecraft_Volume_Beta_NycrypticProject]
		triggers = [ "Dimension-overworld" ]
	[songs.C418_Thirteen_Minecraft_Volume_Alpha_SMORT]
		triggers = [ "Dimension-nether" ]
	[songs.Chrysopoeia_Lena_Raine]
		triggers = [ "Dimension-nether" ]
	[songs.Rubedo_Lena_Raine]
		triggers = [ "Dimension-nether" ]
	[songs.So_Below_Lena_Raine]
		triggers = [ "Dimension-nether" ]
	[songs.C418_Wait_Minecraft_Volume_Beta_NycrypticProject]
		triggers = [ "Dimension-overworld" ]
	[songs.C418_Warmth_Minecraft_Volume_Beta_NycrypticProject]
		triggers = [ "Raining" ]
	[songs.Comforting_Memories_Kumi_Tanioka]
		triggers = [ "Dimension-overworld" ]
	[songs.Floating_Dream_Kumi_Tanioka]
		triggers = [ "Dimension-overworld" ]
	[songs.Infinite_Amethyst_Lena_Raine]
		triggers = [ "Dimension-overworld" ]
	[songs.Left_to_Bloom_Lena_Raine]
		triggers = [ "Dimension-overworld" ]
	[songs.One_More_Day_Lena_Raine]
		triggers = [ "Dimension-overworld" ]
	[songs.Stand_Tall_Lena_Raine]
		triggers = [ "Dimension-overworld" ]


	[songs.A_Brief_Respite_Camp_Theme_Stuart_Chatwood]
		triggers = [ "Time-night" ]
	[songs.A_Dark_Day_In_Aleroth_Divinity_2_Ego_Draconis_OST_astarothification]
		triggers = [ "Height-underground" ]
	[songs.A_New_Dawn_Divinity_2_Ego_Draconis_OST_astarothification]
		triggers = [ "Dimension-overworld", "Raining" ]
	[[songs.A_lagoon_by_mid_day_Sea_Monsters_Official_Soundtrack_Battlechampion47]]
		triggers = [ "Biome-deep_ocean" ]
	[[songs.A_lagoon_by_mid_day_Sea_Monsters_Official_Soundtrack_Battlechampion47]]
		triggers = [ "Biome-ocean" ]
	[songs.Broken_Valley_Wakes_Divinity_2_Ego_Draconis_OST_astarothification]
		triggers = [ "Structure-village" ]
	[songs.Concern_Delicious_in_Dungeon_OST_SoundtracksOST]
		triggers = [ "Dimension-overworld" ]
	[songs.Detective_Harrison_James_10_Crow_Country_Original_Soundtrack_OckeroidMusic]
		triggers = [ "Time-night" ]
	[songs.Divinity_II_Ego_Draconis_music_BV_Farm_tohopes]
		triggers = [ "Structure-village" ]
	[songs.Divinity_II_Ego_Draconis_music_Champions_tohopes]
		triggers = [ "Structure-village" ]
	[songs.Divinity_II_Ego_Draconis_music_Dungeon_BR_tohopes]
		triggers = [ "Dimension-nether" ]
	[songs.Divinity_II_Ego_Draconis_music_Sad_Piano_tohopes]
		triggers = [ "Time-night" ]
	[songs.Dredge_OST_DLC_The_Return_DredgeOST]
		triggers = [ "Biome-ocean" ]
	[songs.Dredge_OST_The_Doldrums_DredgeOST]
		triggers = [ "Biome-ocean" ]
	[songs.Dredge_OST_The_Exotic_Traveller_DredgeOST]
		triggers = [ "Biome-beach" ]
	[songs.Dredge_OST_The_Glass_Journey_DredgeOST]
		triggers = [ "Biome-ocean" ]
	[[songs.Dredge_OST_The_Path_to_the_Door_DredgeOST]]
		triggers = [ "Time-night" ]
	[[songs.Dredge_OST_The_Path_to_the_Door_DredgeOST]]
		triggers = [ "Biome-ocean" ]
	[[songs.Dredge_OST_The_Periphery_DredgeOST]]
		triggers = [ "Biome-ocean" ]
	[[songs.Dredge_OST_The_Periphery_DredgeOST]]
		triggers = [ "Time-night" ]
	[[songs.Dredge_OST_The_Restless_Town_DredgeOST]]
		triggers = [ "Biome-ocean" ]
	[[songs.Dredge_OST_The_Restless_Town_DredgeOST]]
		triggers = [ "Biome-beach" ]
	[songs.Dun_Morogh_Original_Wow_Music_Wowmusicable]
		triggers = [ "Biome-winter" ]
	[songs.Dusk_Stars_Alec_Holowka]
		triggers = [ "time-night" ]
		volume = 0.8
	[[songs.Epiphany_Of_Anguish_Divinity_2_Ego_Draconis_OST_astarothification]]
		triggers = [ "Height-underground" ]
	[[songs.Epiphany_Of_Anguish_Divinity_2_Ego_Draconis_OST_astarothification]]
		triggers = [ "Raining" ]
	[songs.Fireflies_on_the_Porch_Alec_Holowka]
		triggers = [ "time-night" ]
		volume = 0.8
	[songs.Giants_of_the_ocean_Sea_Monsters_Official_Soundtrack_Battlechampion47]
		triggers = [ "Biome-deep_ocean", "Underwater" ]
	[songs.Goblins_No_Time_To_Waste_Divinity_2_Ego_Draconis_OST_astarothification]
		triggers = [ "Raid-default" ]
	[songs.Here_Be_Zandalor_Divinity_2_Ego_Draconis_OST_astarothification]
		triggers = [ "Dimension-overworld" ]
	[songs.Heroes_Of_Might_And_Magic_III_Soundtrack_Ai_Theme_Three_Swaino]
		triggers = [ "Dimension-overworld" ]
	[songs.Heroes_Of_Might_And_Magic_III_Soundtrack_Ai_Theme_Two_Swaino]
		triggers = [ "Dimension-overworld" ]
	[songs.Heroes_Of_Might_And_Magic_III_Soundtrack_Dirt_Theme_Swaino]
		triggers = [ "Biome-desert" ]
	[songs.Heroes_Of_Might_And_Magic_III_Soundtrack_Grass_Theme_Swaino]
		triggers = [ "Dimension-overworld" ]
	[songs.Heroes_Of_Might_And_Magic_III_Soundtrack_Lava_Theme_Swaino]
		triggers = [ "Dimension-nether" ]
	[songs.Heroes_Of_Might_And_Magic_III_Soundtrack_Rough_Theme_Swaino]
		triggers = [ "Dimension-overworld" ]
	[songs.Heroes_Of_Might_And_Magic_III_Soundtrack_Sand_Theme_Swaino]
		triggers = [ "Biome-desert" ]
	[songs.Heroes_Of_Might_And_Magic_III_Soundtrack_Secret_Theme_Swaino]
		triggers = [ "Dimension-nether" ]
	[songs.Heroes_Of_Might_And_Magic_III_Soundtrack_Snow_Theme_Swaino]
		triggers = [ "Biome-winter" ]
	[songs.Heroes_Of_Might_And_Magic_III_Soundtrack_Swamp_Theme_Swaino]
		triggers = [ "Biome-swamp" ]
	[songs.Heroes_Of_Might_And_Magic_III_Soundtrack_Underground_Theme_Swaino]
		triggers = [ "Dimension-overworld" ]
	[songs.Heroes_Of_Might_And_Magic_III_Soundtrack_Water_Theme_Swaino]
		triggers = [ "Biome-ocean" ]
	[songs.Heroes_of_Might_Magic_III_Tower_Town_Theme_1998_NWC_Animated_Khalbrae]
		triggers = [ "Biome-winter" ]
	[songs.Heroes_of_Might_Magic_II_OST_Magnificent_Field_Grassland_Theme_HOMMChannel]
		triggers = [ "Biome-valley" ]
	[songs.Heroes_of_Might_Magic_II_OST_The_Seas_Sea_Theme_HOMMChannel]
		triggers = [ "Biome-ocean" ]
	[songs.Heroes_of_Might_and_Magic_5_Terrain_Grass_Theme_OST_VG_OSTs]
		triggers = [ "Dimension-overworld" ]
	[songs.Heroes_of_Might_and_Magic_5_Terrain_Sand_Theme_OST_VG_OSTs]
		triggers = [ "Biome-desert" ]
	[songs.Heroes_of_Might_and_Magic_5_Terrain_Underground_Theme_OST_VG_OSTs]
		triggers = [ "Dimension-nether" ]
	[songs.Home_Again_Alec_Holowka]
		triggers = [ "Dimension-overworld" ]
		volume = 0.8
	[songs.Illusions_Delicious_in_Dungeon_OST_SoundtracksOST]
		triggers = [ "Dimension-overworld" ]
	[songs.In_The_Kings_Garden_Divinity_2_Ego_Draconis_OST_astarothification]
		triggers = [ "Dimension-overworld" ]
	[songs.In_the_Desolate_Hallways_Dragonspine_Genshin_Impact_OST_Yoshi_Vibes]
		triggers = [ "Biome-winter" ]
	[songs.Inner_Voice_Divinity_2_Ego_Draconis_OST_astarothification]
		triggers = [ "Biome-beach" ]
	[songs.Lullibies_For_Your_Inner_Dragon_Divinity_2_Ego_Draconis_OST_astarothification]
		triggers = [ "Dimension-overworld" ]
	[songs.Majesty_Of_The_Fjords_Divinity_2_Ego_Draconis_OST_astarothification]
		triggers = [ "Biome-mountain" ]
	[songs.Maybe_Everything_Will_Be_Okay_Save_Room_05_Crow_Country_Original_Soundtrack_OckeroidMusic]
		triggers = [ "Time-night" ]
	[[songs.Might_Magic_Heroes_VI_OST_26_Autumn_is_Coming_Siebenbart]]
		triggers = [ "Dimension-overworld" ]
	[[songs.Might_Magic_Heroes_VI_OST_26_Autumn_is_Coming_Siebenbart]]
		triggers = [ "Dimension-overworld" ]
	[songs.Might_Magic_Heroes_VI_OST_5_Ghosts_of_the_Past_Siebenbart]
		triggers = [ "Dimension-overworld" ]
	[songs.Moonlike_Smiles_Dragonspine_Genshin_Impact_OST_Yoshi_Vibes]
		triggers = [ "Biome-winter" ]
	[songs.Ominous_Surroundings_Divinity_2_Ego_Draconis_OST_astarothification]
		triggers = [ "Biome-cave" ]
	[songs.Pumpkin-Hill-_Instrumental_-Sick-Mike]
		triggers = [ "Biome-pumpkin" ]
	[songs.Quarreling_in_Vain_Delicious_in_Dungeon_OST_SoundtracksOST]
		triggers = [ "Dimension-overworld" ]
	[songs.Rainy_Day_Alec_Holowka]
		triggers = [ "Raining" ]
		volume = 0.8
	[songs.Sinister_Mist_Dragonspine_Genshin_Impact_OST_Yoshi_Vibes]
		triggers = [ "Biome-winter" ]
	[songs.Snow_Buried_Tales_Dragonspine_Genshin_Impact_OST_Yoshi_Vibes]
		triggers = [ "Biome-winter" ]
	[songs.Testing_the_ROV_Sea_Monsters_Official_Soundtrack_Battlechampion47]
		triggers = [ "Biome-deep_ocean", "Underwater" ]
	[songs.The_Canaries_Delicious_in_Dungeon_OST_SoundtracksOST]
		triggers = [ "Time-night" ]
	[songs.The_Flourishing_Past_Dragonspine_Genshin_Impact_OST_Yoshi_Vibes]
		triggers = [ "Biome-winter" ]
	[songs.Trilobite_cam_Sea_Monsters_Official_Soundtrack_Battlechampion47]
		triggers = [ "Biome-beach" ]
	[songs.Truth_Revealed_Delicious_in_Dungeon_OST_SoundtracksOST]
		triggers = [ "Structure-village" ]
	[[songs.Undertale_OST_005_Ruins_Misaki]]
		triggers = [ "Height-underground" ]
	[[songs.Undertale_OST_005_Ruins_Misaki]]
		triggers = [ "Time-night" ]
	[songs.Undertale_OST_006_Uwa_So_Temperate_Misaki]
		triggers = [ "Time-night" ]
	[songs.Undertale_OST_017_Snowy_Misaki]
		triggers = [ "Biome-winter" ]
	[songs.Undertale_OST_022_Snowdin_Town_Misaki]
		triggers = [ "Biome-winter" ]
	[songs.Undertale_OST_031_Waterfall_Misaki]
		triggers = [ "Time-night" ]
	[songs.Undertale_OST_054_Hotel_Misaki]
		triggers = [ "Biome-beach" ]
	[songs.Unfinished_Frescoes_Dragonspine_Genshin_Impact_OST_Yoshi_Vibes]
		triggers = [ "Biome-winter" ]
	[songs.Wheres_Casey_Alec_Holowka]
		triggers = [ "Dimension-overworld" ]
		volume = 0.8
	[songs.Wolfstack_Lights_Sunless_Sea_OST_ingame_MagicJinn]
		triggers = [ "Biome-ocean" ]
	[[songs.You_Came_Back_01_Crow_Country_Original_Soundtrack_OckeroidMusic]]
		triggers = [ "Time-night" ]
	[[songs.You_Came_Back_01_Crow_Country_Original_Soundtrack_OckeroidMusic]]
		triggers = [ "Time-night" ]
	[[songs.silence_5min]]
		triggers = [ "Biome-winter" ]
	[[songs.silence_5min]]
		triggers = [ "Biome-beach" ]
	[[songs.silence_5min]]
		triggers = [ "Time-night" ]
	[[songs.silence_5min]]
		triggers = [ "Height-underground" ]
	[[songs.silence_5min]]
		triggers = [ "Structure-village" ]
	[[songs.silence_5min]]
		triggers = [ "Underwater" ]
	[[songs.silence_5min]]
		triggers = [ "Biome-deep_ocean" ]
	[[songs.silence_5min]]
		triggers = [ "Biome-ocean" ]
	[[songs.silence_5min]]
		triggers = [ "Dimension-overworld" ]
	[[songs.silence_5min]]
		triggers = [ "Raining" ]
	[[songs.silence_5min]]
		triggers = [ "Biome-pumpkin" ]
	[[songs.silence_5min]]
		triggers = [ "Raining" ]
	[songs.universal]
		pitch = 1.0
		play_once = 1
		speed = 1.0
		volume = 1.0
		[songs.universal.interrupt_handler]
			priority = 2147483647
			trigger_whitelist = [ ]

[triggers]

	[[triggers.dimension]]
		identifier = "overworld"
		resource_name = [ "minecraft:overworld" ]
	[[triggers.dimension]]
		identifier = "nether"
		resource_name = [ "the_nether" ]
	[[triggers.biome]]
		active_cooldown = 2400
		display_name = [ "basalt_deltas", "crimson_forest", "nether_wastes", "soul_sand_valley", "warped_forest" ]
		identifier = "nether"
		ticks_between_audio = 2400
	[[triggers.biome]]
		display_name = [ "cherry_grove", "frozen_peaks", "jagged_peaks", "meadow", "snowy_slopes", "stony_peaks" ]
		identifier = "mountain"
	[[triggers.biome]]
		display_matcher = "partial"
		display_name = [ "plains" ]
		identifier = "valley"
	[[triggers.biome]]
		display_matcher = "partial"
		display_name = [ "desert", "badlands" ]
		identifier = "desert"
	[[triggers.biome]]
		display_name = [ "deep_cold_ocean", "deep_frozen_ocean", "deep_lukewarm_ocean", "deep_ocean" ]
		identifier = "deep_ocean"
	[[triggers.biome]]
		display_matcher = "partial"
		display_name = [ "cave" ]
		identifier = "cave"
	[[triggers.biome]]
		display_name = [ "cold_ocean", "frozen_ocean", "lukewarm_ocean", "ocean", "warm_ocean" ]
		identifier = "ocean"
	[[triggers.biome]]
		display_name = [ "ice_spikes", "snowy_slopes", "snowy_taiga", "snowy_plains" ]
		identifier = "winter"
	[[triggers.biome]]
		display_name = [ "mangrove_swamp", "swamp" ]
		identifier = "swamp"
	[[triggers.biome]]
		display_matcher = "partial"
		display_name = [ "pumpkin" ]
		identifier = "pumpkin"
	[[triggers.biome]]
		display_matcher = "partial"
		display_name = [ "savanna" ]
		identifier = "savanna"
	[[triggers.biome]]
		display_name = [ "beach", "snowy_beach", "stony_shore" ]
		identifier = "beach"
	[triggers.height]
		identifier = "underground"
		level = 55
		priority = 700
		ticks_before_active = 100
	[triggers.home]
		detection_range = 64
	[triggers.raid]
		active_cooldown = 3600
		identifier = "default"
		ticks_between_audio = 3600
	[triggers.raining]
		persistence = 50
		priority = 400
	[triggers.structure]
		active_cooldown = 2400
		identifier = "village"
		resource_name = [ "village" ]
		ticks_between_audio = 2400
	[[triggers.time]]
		identifier = "night"
		priority = 1001
		time_bundle = "night"
	[[triggers.time]]
		identifier = "day"
		priority = 1001
		time_bundle = "day"
	[triggers.underwater]
		priority = 1400
	[triggers.universal]
		active_cooldown = "1200"
		fade_in = "10"
		fade_out = "150"
		persistence = "400"
		ticks_before_active = "0"
		ticks_before_audio = "0"
		ticks_between_audio = "1200"

